### ISSUE TITLE
405 Not Allowed

### ISSUE THREAD

**Issue by KiaWeb** [OwenTheGoAnimator/Vyond-Legacy-ACS#1]
When I try to sign up, it says 405 not allowed. Can you help?

**Comment by magikalbunny** [comment]
> When I try to sign up, it says 405 not allowed. Can you help?

We are aware, the sign up page wont work. To use the videomaker use this: https://github.com/OwenTheGoAnimator/Vyond-Legacy-ACS/videomaker
