### ISSUE TITLE
Okay real issue this time

### ISSUE THREAD

**Issue by ItsJayPM** [OwenTheGoAnimator/Vyond-Legacy-ACS#5]
This repo does virtually nothing to improve or change wrapper other than to tack on unnecessary html files. You made bold claims of providing accuracy in your old repo yet have nothing to show.

**Comment by DavidB2007** [comment]
isn't it just lovely when a developer targets a kid and tries to raid his server guys, definitely not you!!111!!!

**Comment by magikalbunny** [comment]
1. Your impatient
2. This isnt a fucking lvm clone, its meant for reliving memories. The users are the ones who choose to make content
3. Most of us here are noobs. You think I'm not trying to learn. You think were just being lazy and thinking this project is gonna be a breeze. 
4. You kinda raided the server so fuck off!

**Comment by DavidB2007** [comment]
also bare in mind that jay is literally just a dude who thinks he's all big shot and can boss everyone around, it's rages project, let him do what he wants with it.

**Comment by DavidB2007** [comment]
closing this because you're just complaining for no reason

**Comment by ItsJayPM** [comment]
> 1. Your impatient
> 2. This isnt a fucking lvm clone, its meant for reliving memories. The users are the ones who choose to make content
> 3. Most of us here are noobs. You think I'm not trying to learn. You think were just being lazy and thinking this project is gonna be a breeze.
> 4. You kinda raided the server so fuck off!

1. *You're, also not really you made these promises
2. I never claimed it was a clone, I claimed you made a bunch of ballsy claims you didn't know how to accomplish.
3. Okay? Maybe start smaller.
4. Lol
`

**Comment by ItsJayPM** [comment]
> also bare in mind that jay is literally just a dude who thinks he's all big shot and can boss everyone around, it's rages project, let him do what he wants with it.

BIG SHOT you say? I suppose I am a bit of a [Hyperlink Blocked].

**Comment by ItsJayPM** [comment]
> isn't it just lovely when a developer targets a kid and tries to raid his server guys, definitely not you!!111!!!

I am the same age as you as far as I know, good try though.

**Comment by magikalbunny** [comment]
> > 1. Your impatient
> > 2. This isnt a fucking lvm clone, its meant for reliving memories. The users are the ones who choose to make content
> > 3. Most of us here are noobs. You think I'm not trying to learn. You think were just being lazy and thinking this project is gonna be a breeze.
> > 4. You kinda raided the server so fuck off!
> 
> 1. *You're, also not really you made these promises
> 2. I never claimed it was a clone, I claimed you made a bunch of ballsy claims you didn't know how to accomplish.
> 3. Okay? Maybe start smaller.
> 4. Lol
>    `

Its called learning

**Comment by ItsJayPM** [comment]
> > > 1. Your impatient
> > > 2. This isnt a fucking lvm clone, its meant for reliving memories. The users are the ones who choose to make content
> > > 3. Most of us here are noobs. You think I'm not trying to learn. You think were just being lazy and thinking this project is gonna be a breeze.
> > > 4. You kinda raided the server so fuck off!
> > 
> > 
> > 
> > 1. *You're, also not really you made these promises
> > 2. I never claimed it was a clone, I claimed you made a bunch of ballsy claims you didn't know how to accomplish.
> > 3. Okay? Maybe start smaller.
> > 4. Lol
> >    `
> 
> Its called learning

you learn how to program BEFORE you do the overly ambitious project silly.

**Comment by magikalbunny** [comment]
Bro this is so fucking outdated. Like no cap holy shit I was mentally retarded. Fucking kill me shit fuck fuck fuck

**Comment by Freskim123** [comment]
whats going on in here

**Comment by ghost** [comment]
> > > > 1. Your impatient
> > > > 2. This isnt a fucking lvm clone, its meant for reliving memories. The users are the ones who choose to make content
> > > > 3. Most of us here are noobs. You think I'm not trying to learn. You think were just being lazy and thinking this project is gonna be a breeze.
> > > > 4. You kinda raided the server so fuck off!
> > > 
> > > 
> > > 
> > > 1. *You're, also not really you made these promises
> > > 2. I never claimed it was a clone, I claimed you made a bunch of ballsy claims you didn't know how to accomplish.
> > > 3. Okay? Maybe start smaller.
> > > 4. Lol
> > >    `
> > 
> > 
> > Its called learning
> 
> you learn how to program BEFORE you do the overly ambitious project silly.

i know this is so fucking late but
what about redrawn? i have no experience in js however i hired my friends and people who do know how to code and we've made progress. theres a launcher gui (which is coded in c#), starters, char deleting, more fonts, etc etc etc.

**Comment by NolanJTheSuperGoAnimator** [comment]
Okay now what in the fucking world is going on in here?

**Comment by magikalbunny** [comment]
> > > > 1. Your impatient
> > > > 2. This isnt a fucking lvm clone, its meant for reliving memories. The users are the ones who choose to make content
> > > > 3. Most of us here are noobs. You think I'm not trying to learn. You think were just being lazy and thinking this project is gonna be a breeze.
> > > > 4. You kinda raided the server so fuck off!
> > > 
> > > 
> > > 
> > > 1. *You're, also not really you made these promises
> > > 2. I never claimed it was a clone, I claimed you made a bunch of ballsy claims you didn't know how to accomplish.
> > > 3. Okay? Maybe start smaller.
> > > 4. Lol
> > >    `
> > 
> > 
> > Its called learning
> 
> you learn how to program BEFORE you do the overly ambitious project silly.

Have you know I did learn. I fucking did.

**Comment by NolanJTheSuperGoAnimator** [comment]
And he really IS trying to learn for FUCK'S SAKE

**Comment by magikalbunny** [comment]
> And he really IS trying to learn for FUCK'S SAKE

well its a lot harder than you think

**Comment by NolanJTheSuperGoAnimator** [comment]
And it is harder than usual anyway
